"""Added Contact model in-rel with User

Revision ID: 783b441dbf5d
Revises: f7d379e71a82
Create Date: 2024-03-06 17:54:43.178790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783b441dbf5d'
down_revision = 'f7d379e71a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
